name: Testando GIT Action CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: self-hosted
    steps:
    - name: Step 1
      uses: actions/checkout@v2
      
    - name: Docker Login        
        uses: docker/login-action@v3.4.0
        with:          
          username: 'matheusti828'          
          password: # optional
          
          
 
