name: Testando GIT Action CI

on: 
  push:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-hosted
    steps:
    - name: Step 1
      uses: actions/checkout@v2
      
    - name: Docker Login        
      uses: docker/login-action@v3.4.0
      with:          
        username: 'matheusti828'          
        password: ${{ secrets.SECRET}}

    - name: Build and Push Docker images      
      uses: docker/build-push-action@v6.18.0
      with:    
        context: .
        tags: 'matheusti828/fiap-gitactions:latest'
        push: true
        
          
          
 
